### ISSUE TITLE
NuGet error experience

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1660]
This is an uber bug that I'm using to track NuGet error experience issues:

- [x] [Unloading a project in the middle of large graph can lead to hundreds of errors](https://github.com/NuGet/Home/issues/4724)
- [x] [NuGet spits out large amounts of warnings/errors when you downgrade a package in a large graph](https://github.com/NuGet/Home/issues/4703)
- [x] [Unexpected dependency 'Microsoft.AspNetCore.Razor.Evolution' with no version number" opening MVC/CLI repros](https://github.com/NuGet/Home/issues/4626)
- [x] [Still gets lots of hard to understand errors when you install an incompatible package](https://github.com/NuGet/Home/issues/4555)
- [x] [Add better error handling for the PackTask instead of crashing](https://github.com/NuGet/Home/issues/4472)
- [x] [Get a tonne of unintelligible errors when a project is missing from disk](https://github.com/NuGet/Home/issues/4340)
- [x] [Errors about invalid references are not associated with a project](https://github.com/dotnet/project-system/issues/1160)

**Comment by stonstad** [comment]
I just opened a UWP solution with several projects in VS2017 and I am encountering this "negative experience".   I have 750 downgrade build warnings and not a clue of where to start.  I'm sure there is a version number I need to fix but until then I am here to say how much I dislike this Nuget behavior.  

Surely there is a better way to manage this behavior and the desired response expected from the developer?

**Comment by natidea** [comment]
Much of the work to cleanup these errors has been done, but leaving this as a "Test" to track validating that the experience is better, and eventually to add integration tests

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, unless there are specific actions here.  Moving to 15.4 to get this off the radar.

**Comment by srivatsn** [comment]
Closing this since all the items above have been validated
