### ISSUE TITLE
Lots of UI delays inside Visual Studio when using the project system

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2297]
We're seeing lots of UI delays, more than usual when using the project system, I've seen UI delays when:

1. Expanding nodes in Solution Explorer
2. Add new and removing items to and from the tree
3. Opening C# source files
4. Opening XML files
5. Randomly just pausing while typing

I suspect there's two underlying issues based on the data that I've quickly looked over:

- In my UI delays, lots of GCs everywhere - something is causing a bunch of garbage
- ExecuteSynchronously blocks - maybe ThreadPool is running out of threads?

Please look at mine, @davidfowl and @danroth27 delays when investigating this. ~We do not yet have any traces of these delays.~

We've identified the following issues:

- [x] [Should remove synchronous block from LaunchSettingsProvider](https://github.com/dotnet/project-system/issues/1342) (PR: https://github.com/dotnet/project-system/pull/2317)
- [x] [[Regression] Visual Studio becomes unusable while building if you build with diagnostic results turned on](https://github.com/dotnet/project-system/issues/2379) (PR: https://github.com/dotnet/project-system/pull/2410)
- [x] [[Regression] Visual Studio becomes unresponsive for a long time after opening a large project trying to populate Dependency node](https://github.com/dotnet/project-system/issues/2383) (PR: https://github.com/dotnet/project-system/pull/2400)
- [x] [Opening pinvoke, we're blocking >20 threads in `DependenciesProjectTreeProvider.GetRule` due to a JoinableTaskFactory.Run call](https://github.com/dotnet/project-system/issues/2389) (PR: https://github.com/dotnet/project-system/pull/2392)
- [x] [Extreme contention in OnceInitializedOnceDisposed.EnsureInitialized(bool)](https://github.com/dotnet/project-system/issues/2421) (PR: https://github.com/dotnet/project-system/pull/2429)
- [ ] TODO: Investigate GCs

**Comment by davkean** [comment]
tag @srivatsn @lifengl

**Comment by davkean** [comment]
@srivatsn This has got worse, I'm hitting blocks **all the time** - trying to grab a trace of it...

**Comment by lifengl** [comment]
Then, it would be easy to capture a trace.

Sent from my phone

On May 29, 2017, at 7:40 PM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


@srivatsn<https://github.com/srivatsn> This has got worse, I'm hitting blocks all the time - trying to grab a trace of it...

**Comment by davkean** [comment]
Note, I suspect these are caused by:

1) https://github.com/dotnet/project-system/issues/1342 (PR in review: https://github.com/dotnet/project-system/pull/2317)
2) https://github.com/dotnet/project-system/issues/2379

**Comment by davkean** [comment]
#2 was introduced in 15.3 - hence why it feels like it's got worse in recent builds.

**Comment by davkean** [comment]
A great example of this is: https://github.com/aarnott/pinvoke.  This project is unusable for minutes after it's open.

**Comment by davkean** [comment]
I filed https://github.com/dotnet/project-system/issues/2383 to represent the pinvoke. Looks like that is dependency node population.

**Comment by lifengl** [comment]
#2383 has somewhat a different reason.  The code ran into a scalability problem inside JTF library in the Semaphore related JTF code.

**Comment by davkean** [comment]
@davidfowl @CyrusNajmabadi @Pilchie @sharwell 

Can you do the following to see if performance of the project system is much better for you until we resolve this:

1. Create a file called Directory.Builds.targets with the following contents:

``` XML
<Project>
  <ItemGroup>
    <ProjectCapability Remove="DependenciesTree"/>
  </ItemGroup>
</Project>
```

2. Drop it in the root folder that contains all projects.

This will turn off the Dependencies node.

**Comment by davkean** [comment]
We now have PRs out for all known issues, with exception to the GC delays.

**Comment by Pilchie** [comment]
Tagging @jaredpar here too.  He saw a hang in #2432 that might be related.

**Comment by lifengl** [comment]
@davkean really nice to hear that.  really want to try the product once your fixes are in.

**Comment by davkean** [comment]
@lifengl @sharwell @Pilchie @davidfowl @danroth27 @CyrusNajmabadi 
All known UI delays are now in. They should be available in Friday's build out of PreRel.

There are still three issues that I'm tracking for 15.3 that is affecting general responsiveness of the project system for certain types of projects:

- [Visual Studio constantly consumes ~50 - 90% CPU after opening a large project](https://github.com/dotnet/project-system/issues/2388)
- [Test Window is causing lots of UI delays due to excessive GCs](https://github.com/dotnet/project-system/issues/2445)
- [Visual Studio is running out of memory opening Roslyn.sln](https://github.com/dotnet/project-system/issues/2438)

I'm going to close this bug in lieu of those specific issues.

**Comment by davkean** [comment]
To update the the thread, next week's build should have resolved all known performance regressions. There's still a lot wins to be gained (looks like the new dependency node does a lot more than the previous one) so we'll keep on plowing away on those, please file them as individual issues.

**Comment by aelij** [comment]
@davkean Were these fixes included in the latest preview (July 12)? I've recently converted a large solution (99 projects) to the new project system, and I'm seeing a very degraded experience (in 15.2): the solution loads much slower, and so is opening C# files and building. In the latest preview there was seems to be some improvement but I haven't really measured it so I can't be sure. I can take memory dumps or collect PerfView data if you like.

**Comment by davkean** [comment]
Most of them made into that build - there's still a few that will come in the next build.

Are you saying that 15.3 is better than 15.2? Or are you saying that it's just as bad? Can you file a bug? Traces would be great, even better would be if you could share the source (privately). Can you also "Report a Problem" and put "davkean" in the description - doesn't have to say anything, just lets me see your VS sessions, solution load times, UI delays, etc and figure out what's going on.

**Comment by aelij** [comment]
Yes, 15.3 seems better, but still slower than the previous project system. I'll send a report right now. Should I do it after the solution is open?

**Comment by davkean** [comment]
It doesn't matter when you send the report - it just lets me grab your user data and look at past sessions. Please make sure you open a new bug - so that we're tracking this and we can use to discuss.
