### ISSUE TITLE
Project System: Find in Files should search in project files

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#35]
If you do a Find in Files with a loaded project, VS doesn't search in the project file.

A couple of things to make sure: 

[Find In Solution](https://github.com/dotnet/roslyn-project-system/issues/1292) works
[Open from search results](https://github.com/dotnet/roslyn-project-system/issues/1291) works.

## Current State:

With this in-progess PR: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/124985 (Microsofties-only sorry), the following works:

### What works:
If project file is closed:

- [x] **Find in Files**/**Find All** set to **Project** or **Solution**

If project file is open but not active:

- [x] **Find in Files**/**Find All** set to **Project** or **Solution**
- [x] **Find** set to **Project** or **Solution**

If project file is open and active:

- [x] **Find** set to **Solution**
- [x] **Find in Files**/**Find All** set to **Solution**
- [x] **Incremental Find**

### What doesn't work:

If project file is open and active (**cause:** issue 1):

- [ ] **Find** set to **Project** 
- [ ] **Find in Files**/**Find All** set to **Project** (returns "No files were found to look in")

If project file is closed (**cause:** issue 2):

- [ ] **Find** set to **Project** or **Solution**

If AppDesigner is open (**cause:** issue 3)

- [ ] **Find** set to **Project** or **Solution**

Other:
- [ ] [Attempting to open the project file from Results window displays an error](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/603147)

### Issues that need to be solved:

- [ ] 1. If the project file is open and active, Monitor Service thinks Solution is the active hierarchy and not the project.
- [ ] 2. FindOrOpenFile (FindUtil.cpp) is blocking opening the project file because RDT is returning RDT_ProjSlnDocument. Even if it does return, it asks ShellOpenDocumentService  to OpenDocumentViaProject via LOGVIEWID_TextView.
- [ ] 3. If AppDesigner is open, ShellOpenDocumentService wants to activate it with a different logical view IVsMultiViewDocumentView.ActivateLogicalView

**Comment by sharwell** [comment]
👍 Just hit this today

**Comment by davkean** [comment]
Microsofties, these two PRs are fixing this: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/124985?_a=overview and https://devdiv.visualstudio.com/DevDiv/Default/_git/CPS/pullrequest/124980?_a=overview.

**Comment by gulbanana** [comment]
Definitely running into this recently. The more stuff we put in project files, the more need there is to search them.

**Comment by davkean** [comment]
Duping this against https://github.com/dotnet/project-system/issues/4061 which represents the uber change here.
