### ISSUE TITLE
Finish "project file editing" experience

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4061]
This is a tracking issue for finishing the project file editing:

### Find

If project file is closed:

- [x] **Find in Files**/**Find All** set to **Project** or **Solution** (~#4065~)
- [x] **Find** set to **Project** or **Solution** (~#4065~ & ~#4066~)

If project file is open but not active:

- [x] **Find in Files**/**Find All** set to **Project** or **Solution** (~#4065~)
- [x] **Find** set to **Project** or **Solution** (~#4065~)

If project file is open and active:

- [x] **Find** set to **Solution** (~#4065~)
- [x] **Find in Files**/**Find All** set to **Solution** (~#4065~)
- [x] **Incremental Find** (~#4065~)
- [x] **Find** set to **Project** (~#4065~ & ~#4067~)
- [x] **Find in Files**/**Find All** set to **Project** (returns "No files were found to look in") (~#4065~ & ~#4067~)

If AppDesigner is open

- [x] **Find** set to **Project** or **Solution** (~#4070~)

### Open
- [x] Results window (~#4066~ & ~#4067~)
- [x] Error List (~#4066~ & ~#4067~)
- [x] Preview tab (~#4068~)
- [x] Determine what to do about double-click to open (see OpenProjectEditorOnDefaultActionCommand) - Required, but move to CPS
- [x] File | Open the existing project file should open in text edit mode

### Commands
- [x] Project commands are disabled/hidden when the project file editing is disabled (~#4067~)
- [x] Create double click handler in CPS for provisional tab support (~#4068~)

### Cleanup
- [x] Remove VerifyOpenProjectFileCapability usage inside shell & dialog (~#4071~)
- [x] Remove double click handler from Project System (~#4134~)

### Diff
- [ ] Cannot edit project file in diff mode (~https://developercommunity.visualstudio.com/content/problem/238045/editing-a-csproj-file-through-the-integrated-diffi.html~) (#4215)

**Comment by huoyaoyuan** [comment]
Do you have plan for providing IntelliSense on project files?
When customizing my projects, I often need MSBuild reference to check exact spelling/meaning/value rule for properties. I also need reference when reading (not heavily) customized ones.
Currently, a vsix by Microsoft only provides quick information for nuget package reference.
This is not a trival work, so I want to know your choise on it.

**Comment by Pilchie** [comment]
This is something that's on our backlog, but right now we're focusing on:

1. Performance and scale issues.
2. Reliability issues in NuGet Restore, dependencies node, etc,
3. Support for designers in order to support .NET Core 3.

So it's something we plan to do, but it will likely be a while before we have anything much to show for it.

**Comment by davkean** [comment]
@huoyaoyuan We do provide some IntelliSense:

![image](https://user-images.githubusercontent.com/1103906/47757179-5ffa3280-dcf9-11e8-9a6a-5a06d6877631.png)

Are you saying that you get none? If so, you might be running into https://github.com/Microsoft/msbuild/issues/2787.

**Comment by huoyaoyuan** [comment]
Yes, I get none, even with `xmlns` added. And my VS is not in English too.

**Comment by davkean** [comment]
@huoyaoyuan Can you add information to Microsoft/msbuild#2787 about the particulars of your OS language & VS language?

**Comment by davidwengier** [comment]
Going to close this off as the work has been done, and PRs merged. 

There is still #4215 outstanding however that is an existing issue, and #4222 still needs to be fixed, but they can be tracked individually.

**Comment by cjbush** [comment]
Is there a way to disable double-clicking to edit for csproj files so that it can default to the regular behavior of expanding the node in Solution Explorer?

**Comment by davidwengier** [comment]
It's coming with #4493

**Comment by cjbush** [comment]
Thanks! I missed that one.
