### ISSUE TITLE
FrameworkReference support in Dependencies node

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4762]
Tracking issue for FrameworkReference support in the Dependencies node.

- [x] Project system changes (PR #4928)
- [x] MSBuild `ResolveFrameworkReferences` target stub (PR https://github.com/microsoft/msbuild/pull/4471)
- [x] SDK `ResolveFrameworkReferences` target (PR https://github.com/dotnet/sdk/pull/3355)
- [ ] Verify FrameworkReference browse object (#5070, PR #5230)

**Comment by drewnoakes** [comment]
Duplicated by: 

- https://dev.azure.com/devdiv/DevDiv/_workitems/edit/754156/
- https://dev.azure.com/devdiv/DevDiv/_workitems/edit/820329/
- https://dev.azure.com/devdiv/DevDiv/_workitems/edit/857810/
- https://github.com/dotnet/project-system/issues/4716

**Comment by drewnoakes** [comment]
Note: this issue is about unbreaking the dependencies node experience for .NET Core 3. Issue #4362 is tracking improvements to the UX.

**Comment by drewnoakes** [comment]
Adding `FrameworkReference` items to the tree without any additional filtering logic gives:

![image](https://user-images.githubusercontent.com/350947/59603115-e90c8f80-914b-11e9-9029-025522fe5ec2.png)

Questions at this point:

- [ ] Do framework references expand to show child dependencies?
- [ ] Does it make sense to show both the `Microsoft.WindowsDesktop.App` SDK _and_ Framework?
- [ ] Should the NuGet package used to deliver the framework be hidden, as is done for SDKs today?
- [ ] Is there a better icon for framework references?

//cc: @dsplaisted @nguerrera @cartermp @davkean

**Comment by drewnoakes** [comment]
A more recent screenshot of the same project with the latest .NET Core SDK 3.0.100 preview:

![image](https://user-images.githubusercontent.com/350947/60181630-fa4d4e80-9865-11e9-98ee-6cea9b6d407b.png)

**Comment by drewnoakes** [comment]
Once the MSBuild and SDK PRs are merged and available we'll be able to remove our own stub target and see actual resolved item properties in the browse object.
