### ISSUE TITLE
Dependencies node performance

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5078]
- [ ] Create separate browse object rules for dependency node items (#5076)
- [ ] Design-time build only provides top-level dependencies (#3435)
- [ ] DependencyIDs create a lot of long, duplicate strings (#5051)
- [ ] High CPU when target framework is empty (#3670)
- [ ] Memory allocation in `GetProjectItemSpecsFromSnapshot` (#3548)
- [ ] Dependencies node should share identical subtrees between projects (#3335)
- [ ] Inefficient way to create the first version of the dependencies tree after loading a project (#3321)
- [ ] Failed design-time builds can cause infinite loop of restores (#2867)
- [ ] UpdateTree logic (`BuildTreeForSnapshotAsync`) is too expensive (#2707)
- [ ] Dependency node is doing lots of work on unload (#2640)
- [ ] Move away from returning file paths for dependency nodes that don't need it (#2559)

**Comment by davkean** [comment]
This is replaced with this query: https://github.com/dotnet/project-system/issues?q=is%3Aopen+is%3Aissue+label%3ATenet-Performance+label%3AFeature-Dependency-Node.
