### ISSUE TITLE
Integration Tests TODO:

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5092]
- [x] Test run deployment issues ("Failed to get the file for deployment item 'Context.xml': System.IO.FileNotFoundException: Could not find file 'C:\project-system\artifacts\Debug\bin\IntegrationTests\Context.xml', etc)
- [x] Tests don't run twice in a row (An item with the specified name C:\project-system\artifacts\Debug\TestResults\IntegrationTestTemp already exists)
- [x] VS hive keeps getting reset after running
- [x] VS crashes badly during runs
- [x] RunSettings in ~temp~ intermediate?
- [X] ~create suite.json file (Upload results to AzureDevOps (see #2c594a96)~ Not used anymore.
- [x] Why is xUnit Test Adapter running? (IntegrationTests probably inherits xunit console runner from RoslynToolset)
- [x] Failed to create the Test Contract deployment directory 'C:\Program Files (x86)\Microsoft Visual Studio\2019\master\Common7\IDE\CommonExtensions\TestContracts' in all test runs
- [x] Include `-optimize` flag (per https://github.com/dotnet/project-system/pull/5118/files#r306073290)
- [x] MEF errors when a test fails about trying to resolve attributes from System.Runtime
- [x] Errors around failing to elevate the process for codemarkers and failuring to find ElevateClient.
- [x] Video recording (Apex already does screenshots)
- [x] Validate double writes again (seems xunit is triggering this)
- [x] Fix hive name setting (support both env var and settings file)
- [x] `/diagnostic` option increases log verbosity
- [x] Run a single configuration for integration tests
- [x] Merge and delete `feature/integration-tests` branch
- [x] Fix VS shutdown so that it only shuts down after the last test
- [x] Lower msbuild verbosity on `/diagnostic` once we're happy
- [x] Update VSSDK version (fixes hang due to `/Embedding` flag) #5186
- [x] File bug for broken TRX viewer in dev16.x
- [x] Add `/no-build` option (PR #5190)
- [x] Tests can run from a normal (non-VS) command prompt
- [x] Move `.vsts-ci.yml` into `build` folder and update signed build configuration
- [x] Honour the `RunningUnderCI` property
- [x] Change SetVSEnvironment to limit to 16 once Spanish in on 16.0 (blocked by https://github.com/dotnet/project-system/issues/5176)
- [ ] Suppress first-start dialog (it blocks tests from making progress)
- [ ] Console logging has started logging same stuff as TestContext logging. How do we avoid logging known errors similar to TestContext and do we need TestContext now?
- [ ] What is the timeout for Apex? Can we set it?
  - whole build timeout is in `build/azure-pipelines-integration.yml`
- [ ] Settings seem to be thrown away after running integration tests locally
- [ ] Produce nicer artifacts (no redundant files, better file names, no empty folders...)
- [ ] Make RootSuffix random for CI
- [ ] `<!-- 1. Initialize VS (reset settings, etc) -->`
- [ ] Disable / re-enable Windows Error Reporting (see `DisableWindowsErrorReportingLifetimeAction`)
- [ ] Review data collectors (lots of examples [here](https://devdiv.visualstudio.com/DevDiv/_git/VS#path=%2Fsrc%2FTests%2Fconfig%2Frunsettings%2FRunSettings.targets&version=GBmaster&_a=contents)):
  - [ ] [`LingeringProcessCollector`](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2FTests%2Fconfig%2Frunsettings%2FRunSettings.targets&version=GBmaster&line=55&lineStyle=plain&lineEnd=89&lineStartColumn=1&lineEndColumn=1)
  - [ ] [`ProcDumpCollector`](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2FTests%2Fconfig%2Frunsettings%2FRunSettings.targets&version=GBmaster&line=96&lineStyle=plain&lineEnd=103&lineStartColumn=1&lineEndColumn=1) (`VisualStudioHostConfiguration` also has a `CrashDumpDirectory` property) - looks like we already catch dumps via http://index/?query=DumpCollectorService&rightProject=Microsoft.Test.Apex.Framework&file=Hosts%5CServices%5CDumpCollector%5CDumpCollectorService.cs&rightSymbol=ctwhw4zyyuc6
  - [ ] `SystemInfoDataCollector`
- [ ] Rebase https://github.com/dotnet/project-system/pull/4658 on master
- [ ] Enable triggering integration test CI builds
- [ ] Don't run integration tests on build failure (check if this applies to unit tests too)
- [ ] Read `Common7\IDE\devenv.isolation.ini` and output to console/put in artifacts
- [ ] `OpenProjectTests` failing on @dmonroym's PC (#5268)
- [ ] Update APEX dependencies so they don't reference non-existent packages

**Comment by davkean** [comment]
tag @drewnoakes

**Comment by MiYanni** [comment]
Integration tests will have a separate project/endeavor for getting them working. Current processes require them to be internal based on the tooling used. They will work in a similar manner to how they work in the VS repo itself.
