### ISSUE TITLE
Move IVsHierarchyRefactorNotify notifications to Roslyn

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5436]
Also fixes: https://github.com/dotnet/project-system/issues/1422.

We are [notifying](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Refactor/VisualStudioRefactorNotifyService.cs) projects of renames in the workspace in response to a user renaming a file with a type with the same name, whereas legacy uses CodeModel from Roslyn which does it automatically. We do this so that XAML, RESX and other type consuming things can be notified and updated with the new names.

We should unify this logic into a single service and have both us and CodeModel call it, the lines in particular are this: https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Impl/CodeModel/AbstractCodeModelService.cs#L498-L513.

- [ ] Create a new service in Roslyn that wraps the above lines
- [ ] Change AbstractCodeModelService to call it
- [ ] Provide an API that we can use to consume it

**Comment by davkean** [comment]
This will also fix https://github.com/dotnet/project-system/issues/1422 because this code would also dismiss the rename tracking (as you can see it already does in CodeModel).

**Comment by davkean** [comment]
@ocallesp This might a nice one to bite off, I can probably walk you through doing it during our 1 on 1.

**Comment by drewnoakes** [comment]
> in response to a user renaming a class with a type with the same name

Do you mean "in response to a user renaming a ~class~ _file_ with a type with the same name"

**Comment by davkean** [comment]
Yes.

**Comment by jmarolf** [comment]
The reason we didn't do tbis was that the CodeModel service is not cancelable so if a user begins a symbol rename and wants to cancel it they either need to wait or force the process to stop in task manager.

**Comment by jmarolf** [comment]
Roslyn's internal notification service is cancelable (the one they use for inline rename) but it is not exposed anywhere publicly. If you can get the roslyn team to expose some kind of cancelable api I would love to not need this code.

**Comment by davkean** [comment]
That's what this bug is tracking.

**Comment by jmarolf** [comment]
@davkean 	got it, just didn't see cancellation called out as the blocker.  Thanks for filing this :)

**Comment by jmarolf** [comment]
My hope is that when this is merged: https://github.com/dotnet/roslyn/pull/38488

We could just move all the rename logic over to roslyn itself since they are the real authority on what symbol rename should do. Us needing to re-implement everything like roslyn does is not an ideal long-term solution
