### ISSUE TITLE
Implement new UI for project property pages

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#5776]
This covers the overall work needed to create a new App Designer shell based on the App Capabilities Designer. Individual pieces have been split out into other work items which are now being tracked as dependencies.

- [ ] ~~Add a new assembly to hold the new App Designer. Don't forget setup authoring, loc, and signing.~~ _Split out to #5957._
- [ ] ~~Add a command and command handler to show the new App Designer. Put it behind a Preview Features flag.~~ _Split out to #5958._
- [ ] ~~Create a trivial App Capabilities Designer page with some WPF content, and wire it up to show in the App Capabilities Designer when the command is invoked.~~ _Replaced by #5959._
- [ ] ~~Update the App Capabilities Designer to properly retrieve capabilities from the project in the Cloud Environment.~~ _No longer needed as the set of pages will be completely determined on the server._
- [ ] ~~Update the command to be available in VS Online.~~ _No longer needed as the new App Designer will be available in VS Online to begin with._

**Comment by drewnoakes** [comment]
Closing in favour of #6627.
