### ISSUE TITLE
Project Property Pages

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#6627]
Tracking issue for work on the Project Property Pages UI and back end. The work is split between this repo, CPS and the VS repo.

---

# Project properties

- [x] Review backlog for additional properties (#6720)

### Essential for Preview

- [x] Model display name/underlying value for enums <kbd>0.2</kbd>
- [x] Allow enum property's value to not be in the set of supported values <kbd>0.5</kbd>
- [x] Complete support for essential editor types <kbd>0.5</kbd>
- [x] Support async loading of backing data <kbd>0.5</kbd>
- [x] Get new editor to work in non-Codespaces scenario, for easier development <kbd>1</kbd>
- [x] Add and use a new feature flag <kbd>2</kbd>
- [x] Move code to CPS and get it building <kbd>1</kbd>
  - [x] Use platform's `HighlightTextBlock` <kbd>0.2</kbd>
- [x] Call Project Query API and map data to model <kbd>2</kbd>
- [x] Use VS's image catalog instead of bundling images <kbd>0.5</kbd>
- [x] Reduce property values across invariant dimensions <kbd>1</kbd>
- [x] Integrate help URI <kbd>0.5</kbd>
- [x] Enforce dimension ordering in UI when multiple selected <kbd>0.2</kbd>
- [x] Add support for sending property updates to the server <kbd>2</kbd>
  - [x] Call server
  - [x] Control when update sent (on update, on lose focus, on <kbd>Enter</kbd> etc)
- [x] Conditional property visibility ([PR](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/287643))
  - [x] Model in rule files
  - [x] Evaluate condition expressions on client and update visibility
  - [ ] ~Extend visibility conditions~ (moved to #6907)
    - [ ] ~`(is-sdk-style)`~ (moved to #6907)
    - [ ] ~`(has-capability "GenerateDocumentationFile")` ([SDK source](https://github.com/dotnet/sdk/blob/955c0fc7b06e2fa34bacd076ed39f61e4fb61716/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets#L262-L265))~ (moved to #6907)
    - [ ] ~`(supports-lang-version 8.0)`~ (moved to #6907)
  - [ ] ~Custom functions via MEF?~ (moved to #6895)
- [x] Lock dependent properties during updates and refresh them
  - [x] Support read-only properties (`Property.IsEnabled`)
  - [x] Disable dependent properties while updates are in flight ([PR](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/287643))
  - [x] Refresh property on write and its dependencies
- [x] Determine first approach to eval/uneval value handling in UI <kbd>5</kbd> (see also #6581)
  - [x] Aggregate evaluates value per unevaluated value, and show only unique unevaluated values in UI
  - [x] Tooltip for computed values
  - [x] ~Command to "flatten" computed values~ Allow copying evaluated value within UI
- [ ] ~Introduce MEF contracts and metadata for various types and extension points <kbd>1</kbd>~ (moved to #6895)
  - [ ] ~Property editors~ (moved to #6895)
  - [ ] ~LinkAction handlers~ (moved to #6895)
  - [ ] ~Custom visibility condition functions?~ (moved to #6895)
- [x] Support default value per property type (or per editor type?)
- [x] Introduce `LinkAction` properties as seen in the prototype
  - [x] URL ([PR](https://github.com/tmeschter/roslyn-project-system/pull/2))
  - [ ] ~Action via MEF export (launch debug settings)~ (moved to #6895)
- [ ] ~Prevent content being scrolled off top of screen, especially during search~ (moved to #6906)
- [ ] Editor
  - [x] Document title shouldn't show full path (local) (PR #6732)
  - [x] Local editor sometimes only appears on the second request (PR #6732)
  - [x] Editor (in local scenario) stops project file editor from opening (PR #6732)
  - [x] ~Editor doesn't persist data until user saves &mdash; this should be immediate~
  - [ ] ~Document tab header issues~ (moved to #6897)
    - [ ] ~Show an `*` in the document tab when unsaved changes exist~ (moved to #6897)
    - [ ] ~Tab header text doesn't update if you rename the project~ (moved to #6897)
  - [x] Obtain actual project context in editor to pass to server (PR [288671](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/288671))
- [ ] Bugs
  - [x] Property editors not visible to accessibility
  - [x] Switching dimension variation when aggregating unevaluated values has bugs
  - [x] Fix property menu theming
  - [ ] ~Tab navigation broken when leaving a control in which a change was made~ (moved to #6898)
  - [ ] ~Order of values in target framework drop down (both .NET Core and .NET Framework families) (possibly CPS, maybe [this](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/298982))~ (moved to #6907)
  - [ ] ~`GenerateDocumentationFile` only works with SDK projects (has capability `GenerateDocumentationFile`)~ (moved to #6907)
  - [ ] ~`BaseOutputPath` only works with SDK projects~ (moved to #6907)
  - [ ] ~`BaseOutputPath` shows empty uneval and `bin\` eval~ (moved to #6907)
  - [ ] ~`Nullable` should only be visible when using C# 8 or greater~ (moved to #6907)
  - [ ] ~`Nullable` appearing with nothing selected~ (moved to #6907)
  - [ ] ~Toggling "use multi-targeting" shows a project fault (fix or remove these options)~ (moved to #6907)
  - [ ] ~`Exe` Output Type should be hidden for WPF and WinForms projects in .NET 5 ([more info](https://docs.microsoft.com/en-us/dotnet/core/compatibility/windows-forms/5.0/automatically-infer-winexe-output-type))~ (moved to #6907)
  - [x] Fix search match highlighting <kbd>0.2</kbd>
  - [x] Target framework property should not vary by configuration
  - [x] Category navigation glitches
  - [ ] ~<kbd>Ctrl</kbd>+<kbd>X</kbd> doesn't work in text boxes (code in `PropertyPageElementHost` might be relevant)~ (moved to #6900)
  - [ ] ~Deleting string property value doesn't work. Old value is reinstated on lose focus. Test with "Conditional compilation symbols", "Suppress warnings", "Assembly name"~ (moved to #6899)
- [ ] ~GB18030 compliance testing~ (moved to #6705)

### Essential for GA

- [x] Theming <kbd>1</kbd>
- [x] Move display strings to resource dictionaries for localisation <kbd>0.5</kbd>
  - [ ] ~Set up localisation for string resources~ (moved to #6904)
- [ ] ~Telemetry~ (moved to #6902)
- [x] Accessibility
  - [x] Run accessibility insights tool
    - [x] Fix issues
    - [x] Send update to accessibility team
  - [ ] ~Focus visual style for evaluated value text boxes~ (moved to #6903)
- [x] UI code organisation (push some code into subfolders)
- [x] Search improvements
  - [x] Remove navigation items that contain no results
  - [x] Show the number of results next to the navigation item
  - [x] Ensure selected navigation section tracking works as expected
  - [ ] ~Allow white space in search text (space bar doesn't currently work)~ (moved to #6901)
  - [ ] ~Better support for multiple terms (e.g. "foo bar" should match "foo and bar")~ (moved to #6901)
  - [ ] ~Show a message when search returns no items (currently the UI is completely blank)~ (moved to #6901)

### Potentially important

- [x] Two phase UI building, if getting values is too slow (eg due to having to run DTB)
- [x] Fix occasional minor navigation/scroll positioning bug <kbd>0.5</kbd>
- [x] Look for opportunities to reuse platform code (converters, `ICommand`s, etc)
- [ ] ~Disable dimension per property (eg. TF for Output Path) (reuse visibility conditions?)~ (moved to #6907)
- [ ] ~Disable dimension value per property (eg. prefer 32 bit for x86) (reuse visibility conditions?)~ (moved to #6907)
- [ ] Analyse CPU/allocations
  - [ ] while scrolling
  - [ ] while searching
- [x] UX board review
- [ ] Review use of virtualisation in the property list (currently fails due to grouping)
- [ ] Test scripts for CTI
- [ ] ~Query server on background thread~ (moved to #6905)
- [ ] ~Allow `RegexPattern` metadata for string properties, with client-side validation~ (moved to #6907)

---

## Back end

- [x] Finalize shape of Project Query API, minus dependent property support and updating properties
- [x] Review and merge Project Query API changes to CPS – at this point they can be consumed by the front-end
- [x] Complete implementation of Project Query API in dotnet/project-system, minus dependent property support 
- [x] Review and merge API implementation into dotnet/project-system – at this point the front-end will be able to use the Project Query API to populate the UI
- [x] Finalize shape of dependent property support in Project Query API
- [x] Finalize shape of Project Query API for updating properties
- [x] Complete implementation of Project Query API for updating properties in dotnet/project-system
- [x] Review and merge property updates changes into dotnet/project-system – at this point the front-end will be able to use the Project Query API to update values
- [x] Complete dependent property support in Project Query API in dotnet/project-system
- [x] Review and merge dependent property support into dotnet/project-system
- [ ] ~Collect telemetry for unexpected events (e.g. querying for a page or property that doesn't exist, setting a property that doesn't exist, etc.).~ (moved to #6915)
- [x] `SearchTerms` should be localised (#6742)
- [ ] Update property pages to make use of VisibilityConditions
  - [x] Single targeting vs. multi targeting (i.e. `TargetFramework` and `TargetFrameworks` properties)
  - [x] Resource files vs. icons and manifests
  - [x] Package license expressions vs. package license files. Also, when do we show "Require license acceptance"?
  - [ ] ~Doc comment path (see #368 for related pain and suffering)~ (moved to #6907 for further review)
  - [ ] ~`TreatWarningsAsErrors` plus `WarningsAsErrors` and `WarningsNotAsErrors` (see #2409)~ (moved to #6907)
  - [x] "Startup Object" doesn't apply when "Output Type" is "Class Library" (and possibly others)
  - [ ] ~Prefer 32-bit (?)~ (moved to #6907)
- [ ] Bugs
  - [ ] ~Changes made through Project Query API are not automatically saved to disk~ (moved to #6688)
  - [ ] ~Throw an exception for configuration-dependent updates to configuration-independent properties~ (moved to #6689)
  - [x] Use FWLinks for HelpURLs (#6541)
