### ISSUE TITLE
Re-organize code to support Codespaces

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#6652]
With the advent of Codespaces and the division of Visual Studio into client and server components we can no longer assume that all parts of our features will have direct access to all VS and .NET Project System APIs. We need to refactor our packages to reflect where we expect the related code to run: on the client, on the server, or both.

There are several benefits to this refactoring:

1. It will encourage us to develop new features with a "Codespaces-first" mentality.
2. We can enforce the client/server division at compile time by limiting project dependencies to only those that will be available in the target run time location.
3. It will shrink the size of the client and server SKUs by only including the necessary components in each.

## Design

The proposed set of packages and a high-level overview of how we need to refactor our existing assemblies is captured in the following diagram:

![Package Refactoring (4)](https://user-images.githubusercontent.com/10506730/95110723-53579380-06f3-11eb-9a1d-fd5c7acb7ab6.png)

### Proposed Packages

Note that all four of these packages will be installed in a fully local-only installation.

#### Client

Assemblies and files only needed by the Codespaces client.

#### Server

Assemblies and files only needed by the Codespaces server.

#### Shared

Assemblies and files needed by both the client and server. In practice this is likely to contain the interface and service definitions for Codespaces APIs allowing for the Client and Server packages to communicate, the associated data types, and various bits of utility code.

#### LocalOnly

Contains assemblies with code that doesn't function correctly in Codespaces, and as such should only be available in local-only VS installations. Some features (like the existing property pages) will never make the jump to Codespaces, while others need a place to live for the medium- to long-term until we can rework them to support Codespaces.

### Feature Movement

Features will move into the new packages as follows.

#### Microsoft.VisualStudio.ProjectSystem.Managed

This entire assembly will move to the Server package as-is.

#### Microsoft.VisualStudio.ProjectSystem.Managed.VS

This assembly will move to the Server package except for command handlers, the dialog services, and debug property page support. These will instead move to a new assembly in LocalOnly, Microsoft.VisualStudio.ProjectSystem.Managed.VS.Local. Note that some parts of the debug property page support are public and used by the ASP.NET Core tooling, among others.

#### Microsoft.VisualStudio.AppDesigner

This entire assembly will move to the LocalOnly package.

#### Microsoft.VisualStudio.Editors

Most of this assembly will move to the LocalOnly package. The Resource Editor, however, should be moved to a new assembly in the Client package, Microsoft.VisualStudio.Editors.Client. The options page can be ported to C# and move into Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client.

#### Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client

This entire assembly will move into Client as-is.

## Work Items

- [x] Define new packages. <kbd>4 days</kbd>
- [x] Define new assemblies (including test). <kbd>2 days</kbd>
- [ ] Migrate command handlers to Microsoft.VisualStudio.ProjectSystem.Managed.VS.Local. <kbd>2 days</kbd>
- [x] Migrate dialog services to Microsoft.VisualStudio.ProjectSystem.Managed.VS.Local. <kbd>2 days</kbd>
- [ ] Migrate debug property pages to Microsoft.VisualStudio.ProjectSystem.Managed.VS.Local. <kbd>4 days</kbd>
- [ ] Migrate Resource Editor to Microsoft.VisualStudio.Editors.Client. <kbd>4 days</kbd>
- [ ] Migrate options page to Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client. <kbd>1 day</kbd>
- [ ] Migrate test code
- [ ] Update VS repo to use new packages. <kbd>2 days</kbd>
