### ISSUE TITLE
List of missing properties

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#6720]
(For the list of properties requiring attention see #6907.)

We're missing the below property pages and/or properties from the new Project Properties Designer. Note that this is a list of everything we think is reasonable to consider, and so will contain both items that exist in the old property pages and new items.

- [x] Build events pages and corresponding properties (#5953, PR #6058, PR #7119)
- [ ] ~Code Analysis page~ (moved to #7242)
- [ ] Build page
  - [x] `WarningsNotAsErrors` (#2409)
  - [x] MSBuild "warnings as errors" properties
    - MSBuild has different properties to control when warnings are treated as errors. NuGet seems to re-use the same properties as the C# compiler.
    - [ ] ~`CodeAnalysisTreatWarningsAsErrors`~ (moved to #6793)
  - [x] ~`UseWPF` and `UseWindowsForms`~ (moved to #7239)
  - [x] Debug information (symbols), eg: full, portable (PR #7123)
  - [ ] ~`ProduceReferenceAssembly` (needs investigation)~ (moved to #7245)
- [ ] ~Packaging page~
  - [ ] ~Show new README property~ (Moved to #6457)
- [ ] ~Signing page~
  - [ ] ~"Sign the ClickOnce manifests" property~ (moved to #7244)
- [x] ~VB-specific pages/properties (especially the VB Build page)~ (moved to #6935)
- [x] ~F#-specific pages/properties~ (moved to #6936)
- [x] ~WinForms-specific properties~ (moved to #6937)
- [x] ~WPF-specific properties~ (moved to #6938)
- [ ] .NET Framework-specific properties
  - [x] ~"Auto-generate binding redirects" on the Application page~ (captured by #5940)
  - [ ] ~"Prefer 32-bit" on the Build page~ (moved to #6989)
- [ ] ~"Assembly Information" properties (note some of these are found on the "Package" page; that may not be the best place).~ (moved to #7246)
  - [ ] Title
  - [ ] Description
  - [ ] Company
  - [ ] Product
  - [ ] Copyright
  - [ ] Trademark
  - [ ] Assembly version
  - [ ] File version
  - [ ] GUID
  - [ ] Neutral language
  - [ ] Make assembly COM-Visible (is this .NET Framework-specific?)

**Comment by drewnoakes** [comment]
Remaining items have been split out into separate issues. Closing this.
