### ISSUE TITLE
List of properties requiring attention

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#6907]
(For the list of missing properties, see #6720.)

The following properties are currently included in the UI and require some sort of additional treatment to make them work correctly.

- [x] ~~Order of values in target framework drop down (both .NET Core and .NET Framework families) (possibly CPS, maybe [this](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/298982))~~ Moved to #6989
- [x] `GenerateDocumentationFile` only works with SDK projects (has capability `GenerateDocumentationFile`) (PR #7126)
- [ ] `BaseOutputPath` only works with SDK projects
- [ ] `BaseOutputPath` shows empty uneval and `bin\` eval
- [x] ~~`Nullable` should only be visible when using C# 8 or greater~~ Moved to Moved to #6989
- [x] ~~`Nullable` appearing with nothing selected~~ Moved to Moved to #6989
- [x] ~~Toggling "use multi-targeting" shows a project fault (fix or remove these options)~~ Moved to Moved to #6989
- [ ] `Exe` output type should be hidden for WPF and WinForms projects in .NET 5 ([more info](https://docs.microsoft.com/en-us/dotnet/core/compatibility/windows-forms/5.0/automatically-infer-winexe-output-type))
- [x] Review the behavior of the `GenerateDocumentationFile` and `DocumentationFile` properties on the `Build` page (see #368 for context)
  - [ ] Make sure this works with with both legacy and SDK-style projects
- [x] ~~Rationalize `TreatWarningsAsErrors`, `NoWarn`, `WarningsAsErrors` and `WarningsNotAsErrors` (see #2409 for some context)~~ Moved to Moved to #6989
- [x] ~~"Prefer 32-bit" should show, but only when targeting .NET Framework~~ Moved to Moved to #6989
- [ ] "Conditional compilation symbols" (#6931)
- [ ] "Signing" (strong naming) does not apply when targeting .NET Core. Perhaps we can hide this property in such a case. Need to consider multi-targeting scenario, and case where property is true.
- [x] `ApplicationIcon` needs to copy the file to the project (#7167)

It may be necessary to extend our support for visibility conditions with the following:

- [ ] `(is-sdk-style)`
- [x] `(has-project-capability "GenerateDocumentationFile")` ([SDK source](https://github.com/dotnet/sdk/blob/955c0fc7b06e2fa34bacd076ed39f61e4fb61716/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets#L262-L265)) ([CPS PR](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/317749)) (PR #7126)
- [x] `(supports-lang-version 8.0)`

Potential improvements to editors:

- [ ] Allow `RegexPattern` editor metadata for string properties, with client-side validation

Other more costly options we may need to consider:

- [ ] Disable dimension per property (eg. TF for Output Path) (reuse visibility conditions?)
- [ ] Disable dimension value per property (eg. prefer 32 bit for x86) (reuse visibility conditions?)

**Comment by tmeschter** [comment]
Let's just break out the last three check boxes into their own items and close this.
