### ISSUE TITLE
High-priority list of properties requiring attention (3)

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#6989]
_This work item has been split off of #6907 to contain the highest priority items._

The following properties are currently included in the UI and require some sort of additional treatment to make them work correctly.

- [x] Order of values in target framework drop down (both .NET Core and .NET Framework families) (possibly CPS, maybe [this](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/298982))
  - This may be a bug in our SupportedTargetFrameworksProvider; we may need to do some explicit sorting.
- [x] `Nullable` should only be visible when using C# 8 or greater
  - Possible solution: expose the language version as a hidden property, and condition the visibility of `Nullable` on that.
- [x] ~~`Nullable` appearing with nothing selected~~ Opened https://github.com/dotnet/project-system/issues/7360
  - This is because the SDK doesn't provide a default value for the `<Nullable>` property. We don't currently have a good _general_ solution to this, but it could be handled with an `IInterceptingPropertyValueProvider`: if the property isn't set it could return `disabled` for the value.
- [x] Toggling "use multi-targeting" shows a project fault (fix or remove these options)
  - We should remove the check box, and condition the visibility of the `TargetFramework` and `TargetFrameworks` properties on those properties actually being defined. That way only one or the other will show.
- [x] Rationalize `TreatWarningsAsErrors`, `NoWarn`, `WarningsAsErrors` and `WarningsNotAsErrors` (see #2409 for some context)
  - These properties are all related, so we should make sure the user understands how they work together.
- [ ] "Prefer 32-bit" should show, but only when targeting .NET Framework (PR #7362)
  - When single-targeting we should show this if the target framework is from the .NET Framework family.
  - When multi-targeting, we should show this if *any* of the target frameworks is from the .NET Framework family.

**Comment by tmeschter** [comment]
@jjmew Here's the issue tracking the property page tweaks that I think someone other than me or @drewnoakes could make. I've excluded items that I view as low priority (e.g., changes specifically to support non-SDK projects) or are complex.

@drewnoakes I split these out of #6907. Let me know if there are other things we could include here.

**Comment by drewnoakes** [comment]
@tmeschter @jjmew I think it would be easier to track if these were broken out into separate issues. Priorities can be fluid, and these may be assigned to different people.

**Comment by tmeschter** [comment]
@drewnoakes Per @jjmew's request, I've kept these in a single issue.

**Comment by jjmew** [comment]
@drewnoakes the reason was because I could assign it directly to @MiYanni

**Comment by MiYanni** [comment]
All of these have either been addressed or split into other issues.
