### ISSUE TITLE
Create dev17.2.x branch checklist

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7898]
_Descriptions of these steps can be found in the team OneNote._

- [x] Identify base commit for new branch
  - [x] snapped main to rel/d17.2 at 4PM Feb 4 PST (11AM Feb 5 AEST)
  - [x] Last [completed Project System insertion PR](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequests?_a=completed&createdBy=9f64bc2f-479b-429f-a665-fec80e130b1f&assignedTo=6e89082d-fdd2-4442-a310-051df5bdc73c): https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/377084
  - [x] Last inserted GitHub PR: https://github.com/dotnet/project-system/pull/7876
  - [x] Merge commit: 935b8ad7d226ecf9762045590f2f7fca320eeb4f
- [x] Create branch on GitHub
  - [x] https://github.com/dotnet/project-system/tree/dev17.2.x
- [x] ~For branches not matching `dev*` or `feature/*` (usually we skip these)~
  - [x] ~Update the [YAML file](https://github.com/dotnet/project-system/blob/main/build/ci/unit-tests.yml) to support CI/PR builds~
  - [x] ~Update the [signed build definition](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=9675) to build the new branch~
- [x] Update Roslyn Tools [config.xml](https://github.com/dotnet/roslyn-tools/blob/main/src/GitHubCreateMergePRs/config.xml) file to flow branch changes to the latest dev branch
  - [x] dotnet/roslyn-tools PR: https://github.com/dotnet/roslyn-tools/pull/1169
- [x] ~Update `Versions.props` so `<ProjectSystemVersion>` matches the version of VS, if needed~
    - [x] ~In new branch: https://github.com/dotnet/project-system/blob/dev17.2.x/build/import/Versions.props~
    - [x] ~In `main`: https://github.com/dotnet/project-system/blob/main/build/import/Versions.props~
- [x] Clone existing release definition to insert this branch into VS
  - [x] Waiting on permissions or someone else to fix variable groups (see Teams chat)
- [x] Update [README.md](https://github.com/dotnet/project-system/blob/main/README.md) (in `main`) if we need new badges
- [x] ~Update [MSFTBot milestone tracking](https://aka.ms/fabricbotconfig)~

**Comment by drewnoakes** [comment]
This needs to be done in order to backport #7889 to 17.2 preview 1.

**Comment by drewnoakes** [comment]
This is ready apart from the permission issue with the insertion pipeline's variable groups. See [Teams chat](https://teams.microsoft.com/l/message/19:ba67a1e4184a4f1da5ee42813032ead0@thread.skype/1644215977347?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4ba7372f-2799-4677-89f0-7a1aaea3706c&parentMessageId=1644215977347&teamName=.NET%20Developer%20Experience&channelName=Project%20System&createdTime=1644215977347) for more.

**Comment by drewnoakes** [comment]
Variable groups have been reinstated. This is now done.

**Comment by tmeschter** [comment]
@drewnoakes Is this ready to be closed?
