### ISSUE TITLE
Create dev17.2.x branch checklist

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8036]
_Descriptions of these steps can be found in the team OneNote._

- [x] Identify base commit for new branch
  - [x] According to the [schedule](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/10097/Dev17-Release), `main` snapped to `rel/d17.2` on 1 April 2022 at 4PM PT
  - [x] Last [completed Project System insertion PR](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequests?_a=completed&createdBy=9f64bc2f-479b-429f-a665-fec80e130b1f&assignedTo=6e89082d-fdd2-4442-a310-051df5bdc73c): https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/390040
  - [x] Last inserted GitHub PR: https://github.com/dotnet/project-system/pull/8021
  - [x] Merge commit of that PR: 2d8184bf78a11568ae502597ed5ba6d24bdd736c
- [x] Create branch on GitHub at that commit
  - [x] https://github.com/dotnet/project-system/tree/dev17.2.x
- [ ] ~For branches not matching `dev*` or `feature/*` (usually we skip these)~
  - [ ] ~Update the [YAML file](https://github.com/dotnet/project-system/blob/main/build/ci/unit-tests.yml) to support CI/PR builds~
  - [ ] ~Update the [signed build definition](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=9675) to build the new branch~
- [x] Update Roslyn Tools [config.xml](https://github.com/dotnet/roslyn-tools/blob/main/src/GitHubCreateMergePRs/config.xml) file to flow branch changes to the latest dev branch
  - [x] dotnet/roslyn-tools PR: https://github.com/dotnet/roslyn-tools/pull/1169
- [x] Update `Versions.props` so `<ProjectSystemVersion>` matches the version of VS, if needed
    - [x] In new branch: https://github.com/dotnet/project-system/blob/dev17.2.x/build/import/Versions.props
    - [x] In `main`: https://github.com/dotnet/project-system/blob/main/build/import/Versions.props
- [ ] Clone existing release definition to insert this branch into VS (see OneNote)
- [x] Update [README.md](https://github.com/dotnet/project-system/blob/main/README.md) (in `main`) if we need new badges
- [x] Update [MSFTBot milestone tracking](https://aka.ms/fabricbotconfig)

**Comment by drewnoakes** [comment]
Much of this was already done for an earlier preview in https://github.com/dotnet/project-system/issues/7898.

The main change here is moving the `dev17.2.x` branch forward to the relevant commit from where the branch snapped.
