### ISSUE TITLE
High Priority Accessibility Issues - Sev2 - 17.3

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#8063]
## Summary

Address high impact Sev2s from 17.2 release - 
- [x] [AB#1521198](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1521198)
- [x] #8003
- [x] #8002 (tracked in mega pr)
- [x] #8000 (tracked in PR)
- [x] #7999 (tracked in mega pr)
- [x] #7998 
- [x] #7997 (tracked in mega pr)
- [x] [AB#1504544](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1504544) - NEW (tracked in mega pr)
- [x] [AB#1504993](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1504993) - NEW
- [x] [AB#1504039](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1504039) - NEW
- [x] [AB#1504593](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1504593) - NEW
- [x] [AB#1505024](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1505024) - NEW
- [x] [AB#1505050](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1505050) - NEW
- [x] [AB#1504137](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1504137) - NEW
- [x]  [AB#1504390](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1504390) - NEW
- [x] [AB#1505677](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1505677) - NEW

## User Impact

To improve accessibility experience and compliance
