### ISSUE TITLE
Create dev17.3-preview1 branch checklist

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#8118]
_Descriptions of these steps can be found in the team OneNote._

- [x] Identify base commit for new branch
  - [x] According to the [schedule](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/10097/Dev17-Release), `main` snapped to `rel/d17.3` at 4:00pm PT on April 29th, 2022.
  - [x] Last [completed Project System insertion PR](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequests?_a=completed&assignedTo=6e89082d-fdd2-4442-a310-051df5bdc73c&createdBy=122d5278-3e55-4868-9d40-1e28c2515fc4): https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/395805
  - [x] Last inserted GitHub PR: https://github.com/dotnet/project-system/pull/8110
  - [x] Merge commit of that PR: debe514a304a3e158e33b7a3aaa27c40c2721c69
- [x] Create branch on GitHub at that commit
  - [x] https://github.com/dotnet/project-system/tree/dev17.3-preview1
- [ ] ~~For branches not matching `dev*` or `feature/*` (usually we skip these)~~
  - [ ] ~~Update the [YAML file](https://github.com/dotnet/project-system/blob/main/build/ci/unit-tests.yml) to support CI/PR builds~~
  - [ ] ~~Update the [signed build definition](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=9675) to build the new branch~~
- [x] Update Roslyn Tools [config.xml](https://github.com/dotnet/roslyn-tools/blob/main/src/GitHubCreateMergePRs/config.xml) file to flow branch changes to the latest dev branch
  - [x] dotnet/roslyn-tools PR: https://github.com/dotnet/roslyn-tools/pull/1215
- [x] Update `Versions.props` so `<ProjectSystemVersion>` matches the version of VS, if needed
    - [x] In new branch: https://github.com/dotnet/project-system/blob/dev17.3-preview1/build/import/Versions.props
        - [x] Update PR: https://github.com/dotnet/project-system/pull/8119
    - [x] In `main`: https://github.com/dotnet/project-system/blob/main/build/import/Versions.props
        - [x] Update PR: https://github.com/dotnet/project-system/pull/8120
- [x] Clone existing release definition to insert this branch into VS (see OneNote)
    - Release definition: https://devdiv.visualstudio.com/DevDiv/_releaseDefinition?definitionId=3263&_a=definition-pipeline
    - [x] Link necessary variable group
- [x] Update [README.md](https://github.com/dotnet/project-system/blob/main/README.md) (in `main`) if we need new badges
    - [x] PR: https://github.com/dotnet/project-system/pull/8121 
- [x] Update [MSFTBot milestone tracking](https://aka.ms/fabricbotconfig)

**Comment by tmeschter** [comment]
The work to set up the branch is now complete.
