### ISSUE TITLE
Create dev17.3-preview2 branch checklist

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#8224]
_Descriptions of these steps can be found in the team OneNote._

- [x] Identify base commit for new branch
  - [x] According to the [schedule](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/10097/Dev17-Release), `main` snapped to `rel/d17.3` at 4:00pm PST on 6/3/2022.
  - [x] Last [completed Project System insertion PR](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequests?_a=completed&createdBy=9f64bc2f-479b-429f-a665-fec80e130b1f&assignedTo=6e89082d-fdd2-4442-a310-051df5bdc73c): https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/402508
  - [x] Last inserted GitHub PR: https://github.com/dotnet/project-system/pull/8216
  - [x] Merge commit of that PR: b11e549a143dfb19645abec241bf44dbc5bc2964
- [x] Create branch on GitHub at that commit
  - [x] https://github.com/dotnet/project-system/tree/dev17.3-preview2
- [x] ~~For branches not matching `dev*` or `feature/*` (usually we skip these)~~
  - [x] ~~Update the [YAML file](https://github.com/dotnet/project-system/blob/main/build/ci/unit-tests.yml) to support CI/PR builds~~
  - [x] ~~Update the [signed build definition](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=9675) to build the new branch~~
- [x] Update Roslyn Tools [config.xml](https://github.com/dotnet/roslyn-tools/blob/main/src/GitHubCreateMergePRs/config.xml) file to flow branch changes to the latest dev branch
  - [x] dotnet/roslyn-tools PR: https://github.com/dotnet/roslyn-tools/pull/1230
- [x] Update `Versions.props` so `<ProjectSystemVersion>` matches the version of VS, if needed
    - [x] ~~In new branch: https://github.com/dotnet/project-system/blob/dev17.3-preview2/build/import/Versions.props~~
    - [x] In `main`: https://github.com/dotnet/project-system/blob/main/build/import/Versions.props
        - [x] PR: https://github.com/dotnet/project-system/pull/8225 
- [x] Clone existing release definition to insert this branch into VS (see OneNote)
      Note: I repurposed the dev17.3-preview1 -> rel/d17.3 pipeline for this purpose
- [x] Update [README.md](https://github.com/dotnet/project-system/blob/main/README.md) (in `main`) if we need new badges
    - [x] PR: https://github.com/dotnet/project-system/pull/8226
- [x] Update [MSFTBot milestone tracking](https://aka.ms/fabricbotconfig)
    - [x] PR: https://github.com/dotnet/project-system/pull/8227

**Comment by tmeschter** [comment]
All tasks are complete; closing the issue.
