### ISSUE TITLE
VB Experience - Release Stabilization

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#8243]
##  Summary

Address any customer feedback/fallouts from the VB experience released in 17.3 
- [ ] Revert PR : #8283 and add code generation logic
- [x] #7102
- [x] #6608 - Please note : VB requires that Application Framework is set, without which everything would need to be setup manually. Not blocking, given that it application framework can be reselected for it to work
- [x] #8258
- [ ] #8286
- [x] [AB#1566265](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1566265)
- [x] #8436 - Duplicate of feedback ticket : [AB#1597634](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1597634)
- [X] #8538

## User Impact
Decrease in negative feedback and increase in positive feedback. All Property related features function as expected. Positive feedback from customer on the new VB user experience addressed

## Issues related
- #8257 
- #6608 
- [Lower priority] #8259 
- [Lower priority] #8258

**Comment by melytc** [comment]
Work left here: generate code for the new properties (currently waiting for API changes in https://github.com/dotnet/project-system/pull/8044).

**Comment by kvenkatrajan** [comment]
Moved remaining items to : #8766 for 17.6. Closing 17.5 stabilization ticket.
