### ISSUE TITLE
Validation of Impact of Configuration Switch Optimization on Language Service Initialization

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#8300]
@## Summary

This is a placeholder item to validate the performance improvements for Configuration switch optimization code
- [x] Functional Testing : #7541
- [x] Validate if #7615 occurs
- [x] Validate if [AB#1439046](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1439046) occurs
- [x] Coordinate with Roslyn team to add speedometer test for this scenario
- [x] Add/use telemetry values to capture time from configuration switch to intellisense

## Impact
Will help identify the impact & add tests to identify regression in the future
