### ISSUE TITLE
Create dev17.4-preview1 branch checklist

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#8366]
_Descriptions of these steps can be found in the team OneNote._

- [x] Identify base commit for new branch
  - [x] According to the [schedule](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/10097/Dev17-Release), `main` snaps to `rel/d17.4` at 4:00 PST on July 29th, 2022.
  - [x] ~~Last [completed Project System insertion PR](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequests?_a=completed&createdBy=9f64bc2f-479b-429f-a665-fec80e130b1f&assignedTo=6e89082d-fdd2-4442-a310-051df5bdc73c): https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/411729~~
  - [x] ~~Last inserted GitHub PR: https://github.com/dotnet/project-system/pull/8330~~
  - [x] ~~Merge commit of that PR: c872cfac0ca7960961bbc1e9d92fb2dfd4c0df9d~~
  - [x] Last [completed Project System insertion PR](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequests?_a=completed&createdBy=9f64bc2f-479b-429f-a665-fec80e130b1f&assignedTo=6e89082d-fdd2-4442-a310-051df5bdc73c): https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/414176
  - [x] Last inserted GitHub PR: https://github.com/dotnet/project-system/pull/8365
  - [x] Merge commit of that PR: 30f69af46826164e89a665e99c6f066fb4e2caec
- [x] Create branch on GitHub at that commit
  - [x] https://github.com/dotnet/project-system/tree/dev17.4-preview1
- [x] ~~For branches not matching `dev*` or `feature/*` (usually we skip these)~~
  - [x] ~~Update the [YAML file](..\\..\eng\pipelines\unit-tests.yml) to support CI/PR builds~~
  - [x] ~~Update the [signed build definition](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=9675) to build the new branch~~
- [x] Update Roslyn Tools [config.xml](https://github.com/dotnet/roslyn-tools/blob/main/src/GitHubCreateMergePRs/config.xml) file to flow branch changes to the latest dev branch
  - [x] dotnet/roslyn-tools PR: https://github.com/dotnet/roslyn-tools/pull/1257
- [ ] Update [Versions.props](..\\..\eng\imports\Versions.props) (via `<ProjectSystemVersion>`) and [version.json](..\\..\version.json) (via `"version"` and `"assemblyVersion"`) to match the version of VS, if needed
    - **NOTE:** We do not think this is necessary. Skipping for the moment.
    - [ ] In new branch: https://github.com/dotnet/project-system/blob/dev17.❓.x/eng/imports/Versions.props
    - [ ] In `main`: https://github.com/dotnet/project-system/blob/main/eng/imports/Versions.props
- [x] Clone existing release definition to insert this branch into VS (see OneNote)
    - [x] Clone release definition: https://devdiv.visualstudio.com/DevDiv/_releaseDefinition?definitionId=3295
    - [x] Re-link variable group
- [x] ~~Update [README.md](https://github.com/dotnet/project-system/blob/main/README.md) (in `main`) if we need new badges~~
    - **NOTE:** Not bothering for a Preview branch.
- [x] Update [MSFTBot milestone tracking](https://aka.ms/fabricbotconfig)
    - [x] PR: https://github.com/dotnet/project-system/pull/8367 
- [x] Delete and recreate dev17.4-preview1 branch to based on actual snap from `main` to `rel/d17.4` (if needed).

**Comment by MiYanni** [comment]
This work has been completed.
