### ISSUE TITLE
Create upstream/dev17.4-preview2 branch checklist

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8458]
_Descriptions of these steps can be found in the team OneNote._

- [x] Identify base commit for new branch
  - [x] According to the [schedule](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/10097/Dev17-Release), `main` snapped to `rel/d17.4` at 2 Sep 4 PM PT
  - [x] Last [completed Project System insertion PR](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequests?_a=completed&createdBy=9f64bc2f-479b-429f-a665-fec80e130b1f&assignedTo=6e89082d-fdd2-4442-a310-051df5bdc73c): https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/420801
  - [x] Last inserted GitHub PR: https://github.com/dotnet/project-system/pull/8450
  - [x] Merge commit of that PR: 2299b02e7647d88033b352daff38368c8a9611db
- [x] Create branch on GitHub at that commit
  - [x] https://github.com/dotnet/project-system/tree/dev17.4-preview2
- [x] ~For branches not matching `dev*` or `feature/*` (usually we skip these)~
  - [x] ~Update the [pull-request.yml](..\\..\eng\pipelines\pull-request.yml) (via `pr`) to support PR builds~
  - [x] ~Update the [official.yml](..\\..\eng\pipelines\official.yml) (via `trigger`) to have signed builds the new branch~
- [x] Update Roslyn Tools [config.xml](https://github.com/dotnet/roslyn-tools/blob/main/src/GitHubCreateMergePRs/config.xml) file to flow branch changes to the latest dev branch
  - [x] dotnet/roslyn-tools PR: https://github.com/dotnet/roslyn-tools/pull/1272
- [x] ~Update [version.json](../../version.json) (via `"version"`) to match the version of VS, if needed~
    - [ ] ~In new branch: https://github.com/dotnet/project-system/blob/dev17.4-preview2/version.json~
    - [ ] ~In `main`: https://github.com/dotnet/project-system/blob/main/version.json~
- [ ] For running manual insertions, queue them up within the [DotNet-Project-System pipeline](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=9675&_a=summary) and enter the appropriate `VS Insertion Branch Name`
- [x] ~Update [README.md](https://github.com/dotnet/project-system/blob/main/README.md) (in `main`) if we need new badges~
- [x] Update [MSFTBot milestone tracking](https://aka.ms/fabricbotconfig)
  - [x] https://github.com/dotnet/project-system/pull/8459

**Comment by drewnoakes** [comment]
Note: The actual PR we snapped from was #8419 (5896b880c19071eb34c0e9966295c41d2bb44142). I'm using #8450 (2299b02e7647d88033b352daff38368c8a9611db) instead, as it fixes the build pool names (and comes immediately after). This avoids having to cherry-pick that commit onto the new branch.
