### ISSUE TITLE
Resource Management Enhancements

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#8533]
This is a placeholder for the prototype and CDE features based on effort/impact matrix. 

- [x] UI prototype for outlining flow of create a resource from a string/variable
- [x] UI prototype for outlining flow of search and filter for an asset/string/similar strings by category, tag, ID or stringValue
- [x] UI prototype for display of search results and asset details
- [x] UX board review : https://devdiv-design.visualstudio.com/D3%20Studio/_workitems/edit/17756
- [x] Refactoring to move string literal from code to resource
- [x] Placeholder validation
- [ ] <del>Export/import string resources into different file formats (excel, csv, txt)</del>
