### ISSUE TITLE
Highest score Feedback tickets and bugs - 17.5

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#8534]
High priority feedback tickets and bugs 

- [x] [AB#1449788](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1449788) Default csproj indentation does not match templates or dotnet new
- [ ] #8014 
- [ ] [AB#1274456](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1274456) Conflict with *.user and launchSettings.json. 
- [x] [AB#1618367](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1618367) Error List not clearing after when loading different solution
- [x] [AB#1712009](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1712009) Unable to change Target Framework - Project system data flow 'UpToDateCheckImplicitConfiguredInputDataSource: 15593218' closed because of an exception
- [x] #8537
- [x] #6931 
- [x] [AB#1684727](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1684727) VS 2022 Pro hangs and restarts when loading Sdk project properties
- [x] [AB#1707846](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1707846) Visual Studio crashes when opening project properties
- [x] [AB#1576601](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1576601) - [Feedback] Debugging Xunit tests is not able to hit breakpoints
