### ISSUE TITLE
Create upstream/dev17.4.x branch checklist

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#8562]
_Descriptions of these steps can be found in the team OneNote._

- [x] Identify base commit for new branch
  - [x] According to the [schedule](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/10097/Dev17-Release), `main` snapped to `rel/d17.4` at 9/30 at 4pm PST
  - [x] Last [completed Project System insertion PR](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequests?_a=completed&assignedTo=6e89082d-fdd2-4442-a310-051df5bdc73c): https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/426301
  - [x] Last inserted GitHub PR: https://github.com/dotnet/project-system/pull/8540
  - [x] Merge commit of that PR: 583c3f3c0f54e4f569e90d2477b01b796ad010ae
- [x] Create branch on GitHub at that commit
  - [x] https://github.com/dotnet/project-system/tree/dev17.4.x
- [ ] ~For branches not matching `dev*` or `feature/*` (usually we skip these)~
  - [ ] ~Update the [pull-request.yml](https://github.com/dotnet/project-system/blob/main/eng/pipelines/pull-request.yml) (via `pr`) to support PR builds~
  - [ ] ~Update the [official.yml](https://github.com/dotnet/project-system/blob/main/eng/pipelines/official.yml) (via `trigger`) to have signed builds the new branch~
- [x] Update Roslyn Tools [config.xml](https://github.com/dotnet/roslyn-tools/blob/main/src/GitHubCreateMergePRs/config.xml) file to flow branch changes to the latest dev branch
  - [x] dotnet/roslyn-tools PR: https://github.com/dotnet/roslyn-tools/pull/1283
- [ ] ~Update [version.json](https://github.com/dotnet/project-system/blob/main/version.json) (via `"version"`) to match the version of VS, if needed~
    - [ ] ~In new branch: https://github.com/dotnet/project-system/blob/dev17.❓.x/version.json~
    - [ ] ~In `main`: https://github.com/dotnet/project-system/blob/main/version.json~
- [x] For running manual insertions, queue them up within the [DotNet-Project-System pipeline](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=9675&_a=summary) and enter the appropriate `VS Insertion Branch Name`
- [ ] ~Update [README.md](https://github.com/dotnet/project-system/blob/main/README.md) (in `main`) if we need new badges~
- [x] Update [MSFTBot milestone tracking](https://aka.ms/fabricbotconfig)
  - [x] https://github.com/dotnet/project-system/pull/8563
