### ISSUE TITLE
Create dev17.5-preview2 branch checklist

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8704]
_Descriptions of these steps can be found in the team OneNote._

- [x] Identify base commit for new branch
  - [x] According to the [schedule](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/10097/Dev17-Release), `main` snapped to `rel/d17.5` at 2 Dec 4PM PST
  - [x] Last [completed Project System insertion PR](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequests?_a=completed&assignedTo=6e89082d-fdd2-4442-a310-051df5bdc73c): https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/438334
  - [x] Last inserted GitHub PR: https://github.com/dotnet/project-system/pull/8694
  - [x] Merge commit of that PR: 07a6c3f1e59fdc8e590773810042bcd1efd1aabe
- [x] Create branch on GitHub at that commit
  - [x] https://github.com/dotnet/project-system/tree/dev17.5-preview2
- [x] For branches not matching `dev*` or `feature/*` (usually we skip these)
  - [x] Update the [pull-request.yml](https://github.com/dotnet/project-system/blob/main/eng/pipelines/pull-request.yml) (via `pr`) to support PR builds
  - [x] Update the [official.yml](https://github.com/dotnet/project-system/blob/main/eng/pipelines/official.yml) (via `trigger`) to have signed builds the new branch
- [x] Update Roslyn Tools [config.xml](https://github.com/dotnet/roslyn-tools/blob/main/src/GitHubCreateMergePRs/config.xml) file to flow branch changes to the latest dev branch
  - [x] dotnet/roslyn-tools PR: https://github.com/dotnet/roslyn-tools/pull/1300
- [ ] ~Update [version.json](https://github.com/dotnet/project-system/blob/main/version.json) (via `"version"`) to match the version of VS, if needed~
    - [ ] ~In new branch: https://github.com/dotnet/project-system/blob/dev17.❓.x/version.json~
    - [ ] ~In `main`: https://github.com/dotnet/project-system/blob/main/version.json~
- [ ] For running manual insertions, queue them up within the [DotNet-Project-System pipeline](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=9675&_a=summary) and enter the appropriate `VS Insertion Branch Name`
- [ ] Update [README.md](https://github.com/dotnet/project-system/blob/main/README.md) (in `main`) if we need new badges
- [ ] Update [MSFTBot milestone tracking](https://aka.ms/fabricbotconfig)
