### ISSUE TITLE
Highest score Feedback tickets and bugs - 17.6

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#8755]
## Summary

High priority feedback tickets and bugs

- [x] [AB#1556693](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1556693) Moving a location of an unsaved file within Visual Studio explore will result in losing changes.
- [x] [AB#1745651](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1745651) VS hang when closing Maui solution immediately after opening - StartupProjectRegistrar blocks project unload
- [x] [AB#1741242](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1741242) Changes to application settings in VB.net Project seems to incorrectly update Global.My.Mysettings to Global.My.My.MySettings
- [x] [AB#1707957](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1707957) Can't set an Output Path to a VB.NET .NET 7 project

## User Impact
These are priority 0 or 1 feedback tickets and need to be addressed in the upcoming release
