### ISSUE TITLE
Highest score - Feedback tickets & bugs - 17.7 - P1

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#8941]
## Summary

- [x] [AB#1714657](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1714657) Cannot modify Trademark or File Description assembly attributes in SDK projects in project properties UI
- [x] [AB#1430819](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1430819) [WinUI]There was a error after updating target platform from 5.0 to 6.0.
- [x] #8931 
- [x] [AB#1743403](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1743403)
- [x]  [AB#1274456](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1274456) - Conflict with *.user and launchSettings.json - Warn user on conflict
- [x] #8937

## User Impact

These are priority 0 feedback tickets and need to be addressed in the upcoming release
