### ISSUE TITLE
Build Acceleration - Default to On

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#9106]
## Summary

In 17.5 [Build Acceleration](https://github.com/dotnet/project-system/blob/main/docs/build-acceleration.md) was released as an opt in feature and this had significant impact on build performance as detailed in the [discussion board](https://github.com/dotnet/project-system/discussions/8871)
Next Step is to turn this on by default. 

Considerations
- Ability to turn on feature flag remotely and measurably increase the span of audience 
- Iron out any devbox implications
- Identify installer projects and disable
- Identify true impact on pre/post build

## User Impact

~80% increase in build performance:

- [From 224sec to 5 sec](https://github.com/dotnet/project-system/issues/8865#issuecomment-1441746389)
- [From 26 to 1.5 sec](https://twitter.com/rothdave/status/1628330450484600833)
- [Consistent 8sec in VS](https://twitter.com/maartenballiauw/status/1646486372000182274)

## Tasks

- [x] Add feature flag to VS https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/486390
- [x] Add code to check the feature flag https://github.com/dotnet/project-system/pull/9181
- [x] Improve logging to improve awareness of the changed default https://github.com/dotnet/project-system/pull/9181
- [x] Address known limitations
  - [x] https://github.com/dotnet/project-system/pull/9214
  - [x] https://github.com/dotnet/project-system/pull/9257
  - [x] https://github.com/dotnet/project-system/pull/9258
- [x] Opt in internal developers
- [x] Allow the feature flag to be publicly visible https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/496924
- [x] Change the feature flag to default to on https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/496925
- [ ] Update documentation to explain use of the new feature flag

**Comment by LevYas** [comment]
Hi, thanks for the improvement. In which version of VisualStudio it is set to ON?
I try to understand, whether I still need to specify the acceleration per project or not.

**Comment by kvenkatrajan** [comment]
hi @LevYas  thanks for your interest. This has been turned on by default in 17.9 release for sdk style (.NET core) projects.

**Comment by govert** [comment]
The default setting for build acceleration changed in VS 17.9 (according to the last internal VS check-ins referenced in this issue).  We are building SDK-style projects that target .NET Framework, and for our projects this update turned out to be a surprising and hard-to-track-down breaking change. (Even though the previous comment suggests it changed for "sdk style (.NET core) projects", our sdk style (.NET Framework)" project was affected.) The default changed with no indication in the Visual Studio release notes. 

The behavior of the "FastUpToDate" build is different to the normal MSBuild in that additional transitive dependencies are copied to the output, where MSBuild would not copy these files. With build acceleration on, the extra files will be copied to output when either doing "Build" or starting to debug, which both trigger the "FastUpToDate" build and hence the extra copy. When doing a "Rebuild" or building after changes, the real MSBuild build is run, which does not copy the extra files. This is even more confusing, since extra files will remain in the output until manually deleted ("Clean" runs MSBuild, which will not remove the extra files).

Whether the extra files should be there or not is another matter, but having these two incompatible build behaviors is very confusing. In our case these files were not used, but broke things at runtime. 

Furthermore, there are now two settings in Visual Studio with unclear interaction.
* Tools -> Options -> Environment -> Preview Features -> Enable Build Acceleration By Default
* Tools -> Project and Solutions -> SDK-Style Projects -> Up to Date Checks

in additional to the explicit project property `<AccelerateBuildsInVisualStudio>`.

It would be helpful to clean up and document these options, and to document this breaking change in the release notes for Visual Studio.

Finally, it would be helpful to know why the build behavior is different (why additional files are copied as part of the "FastUpToDate" build which would not be copied by a real MSBuild build). Even if there is an argument for why these files _should_ be in the output, neither MSBuild builds nor previous Visual Studio version would put them there. One would expect the accelerated build in Visual Studio to only be an optimization and not introduce changed behavior.

**Comment by drewnoakes** [comment]
@govert we definitely want parity between MSBuild and Build Acceleration. Could you verify whether the issue you're seeing is the same as #9001 or #8728? If not, please file a new issue and include enough information to repro the problem, so we can investigate. Thank you and sorry for the trouble here.

**Comment by Maintenance-Partnership-Systems** [comment]
Hmm. I think I just opened another issue that relates to this topic - see https://github.com/dotnet/project-system/issues/9416#issue-2180671041
