### ISSUE TITLE
Resource Designer - VS Integration and Persistence

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#9112]
## Summary

This is tracked at : https://dev.azure.com/devdiv/DevDiv/_queries/edit/1863072/?queryId=d1e1bb7f-1f7b-4f52-8d60-80da46fd8541
The goal is to integration the modern UI experience for the resource designer prototype into Visual Studio

- [x] https://github.com/drewnoakes/resource-explorer-prototype/issues/80 [S]
- [x] https://github.com/drewnoakes/resource-explorer-prototype/issues/233 [S]
- [x] https://github.com/drewnoakes/resource-explorer-prototype/issues/143 [M]
- [x] https://github.com/drewnoakes/resource-explorer-prototype/issues/232 [S]
- [x] https://github.com/drewnoakes/resource-explorer-prototype/issues/234 [M] (needs additional design discussion)
- [ ] [#8038](https://github.com/dotnet/project-system/issues/8038)
