### ISSUE TITLE
Create dev17.7.x branch checklist

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#9163]
_Descriptions of these steps can be found in the team OneNote._

- [x] Identify base commit for new branch
  - [x] According to the [schedule](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/10097/Dev17-Release), `main` snapped to `rel/d17.7` on 30 June at 2:00PM PST
  - [x] Last [completed Project System insertion PR](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequests?_a=completed&assignedTo=6e89082d-fdd2-4442-a310-051df5bdc73c): https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/481465
  - [x] Last inserted GitHub PR: https://github.com/dotnet/project-system/pull/9132
  - [x] Merge commit of that PR: ebb70e2938840a37c6e44c5c30d55f3d4e9d9a4b
- [x] Create branch on GitHub at that commit
  - [x] https://github.com/dotnet/project-system/tree/dev17.7.x
- [x ~For branches not matching `dev*` or `feature/*` (usually we skip these)~
  - [x] ~Update the [pull-request.yml](https://github.com/dotnet/project-system/blob/main/eng/pipelines/pull-request.yml) (via `pr`) to support PR builds~
  - [x] ~Update the [official.yml](https://github.com/dotnet/project-system/blob/main/eng/pipelines/official.yml) (via `trigger`) to have signed builds the new branch~
- [x] Update Roslyn Tools [config.xml](https://github.com/dotnet/roslyn-tools/blob/main/src/GitHubCreateMergePRs/config.xml) file to flow branch changes to the latest dev branch
  - [x] dotnet/roslyn-tools PR: https://github.com/dotnet/roslyn-tools/pull/1359
- [x] Update [version.json](https://github.com/dotnet/project-system/blob/main/version.json) (via `"version"`) to match the version of VS, if needed
    - [x] ~In new branch: https://github.com/dotnet/project-system/blob/dev17.7.x/version.json~
    - [x] In `main`: https://github.com/dotnet/project-system/blob/main/version.json
       - https://github.com/dotnet/project-system/pull/9164
- [ ] For running manual insertions, queue them up within the [DotNet-Project-System pipeline](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=9675&_a=summary) and enter the appropriate `VS Insertion Branch Name`
- [x] Update [MSFTBot milestone tracking](https://aka.ms/fabricbotconfig)
   - https://github.com/dotnet/project-system/pull/9166
