### ISSUE TITLE
Highest Score - Feedback tickets and bugs 

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#9206]
## Summary
- [x] [AB#1861138](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1861138)
- [x] [AB#1693387](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1693387)
- [x] [AB#1783493](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1783493) - VS 2022 17.4 is breaking the VB Settings.Designer.vb file which were created with VS 2022 17.0
- [x] [AB#1867244](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1867244) - With clean install of VS 17.8 P1 without 6.0/7.0 runtime installed, if we open a console app or web app targeting net6.0, we don't see a gold-bar indicating that the runtime is not installed
- [x] [AB#1846189](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1846189) - Keep TargetPlatformVersion value when changing a WinUI project's target framework
- [x] [AB#1833295](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1833295) - NFE
- [x] #9220 
- [x] [AB#1847450](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1847450) - NFE

## User Impact

These are priority 0 feedback tickets/hangs  and need to be addressed in the upcoming release
