### ISSUE TITLE
dev17.8.x branch checklist

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#9282]
_Descriptions of these steps can be found in the team OneNote._

- [x] Identify base commit for new branch
  - [x] According to the [schedule](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/10097/Dev17-Release), `main` snapped to `rel/d17.8` on Sept. 29th at 12:00pm PST
  - [x] Last [completed Project System insertion PR](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequests?_a=completed&assignedTo=6e89082d-fdd2-4442-a310-051df5bdc73c): https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/500515
  - [x] Last inserted GitHub PR: https://github.com/dotnet/project-system/pull/9273
  - [x] Merge commit of that PR: 9b283388092c9c30f8b2be0013846473bfb3cbd8
- [x] Create branch on GitHub at that commit
  - [x] https://github.com/dotnet/project-system/tree/dev17.8.x
- [ ] ~~For branches not matching `dev*` or `feature/*` (usually we skip these)~~
  - [ ] ~~Update the [pull-request.yml](https://github.com/dotnet/project-system/blob/main/eng/pipelines/pull-request.yml) (via `pr`) to support PR builds~~
  - [ ] ~~Update the [official.yml](https://github.com/dotnet/project-system/blob/main/eng/pipelines/official.yml) (via `trigger`) to have signed builds the new branch~~
- [x] Update Roslyn Tools [config.xml](https://github.com/dotnet/roslyn-tools/blob/main/src/GitHubCreateMergePRs/config.xml) file to flow branch changes to the latest dev branch
  - [x] dotnet/roslyn-tools PR: https://github.com/dotnet/roslyn-tools/pull/1364
- [x] Update [version.json](https://github.com/dotnet/project-system/blob/main/version.json) (via `"version"`) to match the version of VS, if needed
    - [ ] ~~In new branch: https://github.com/dotnet/project-system/blob/dev17.8.x/version.json~~ Nothing to do here.
    - [x] In `main`: https://github.com/dotnet/project-system/blob/main/version.json: #9283
- [ ] To run manual insertions, use the [DotNet-Project-System pipeline](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=9675&_a=summary). Enter the GitHub branch as _Branch/tag_, the VS branch as _VS Insertion Branch Name_, and check _Create VS Insertion PR_.
- [x] Update [MSFTBot milestone tracking](https://aka.ms/fabricbotconfig): #9285

**Comment by tmeschter** [comment]
I'm calling this complete.
